### ISSUE TITLE
Detecting UEFI/BIOS config in WinPE

### ISSUE THREAD

**Issue by motorhead018** [windows-admins/ConfigMgr#58]
Please look into the detection of UEFI/BIOS config while in WinPE.

**Comment by RowdyChildren** [comment]
There are already built in vars for this.

**Comment by Ebag333** [comment]
Incorrect. There are built in vars to detect how you boot, not what the BIOS is set to.

But you already know this. :troll:

**Comment by RowdyChildren** [comment]
It wasn't worded well but I saw the context on slack now

**Comment by motorhead018** [comment]
@Tom's Second Lover What other information could I/we provide?

**Comment by ajf8729** [comment]
Closing as a stale request, please open a new issue if this persists.
