### ISSUE TITLE
Script out some PoSh creating a DIAD structure

### ISSUE THREAD

**Issue by Ebag333** [windows-admins/ConfigMgr#72]
https://docs.microsoft.com/en-us/windows-server/identity/securing-privileged-access/privileged-access-workstations

**Comment by theaquamarine** [comment]
For 'in-domain' PAWs, Microsoft's setup scripts are on github at https://github.com/Microsoft/PAWTools, and John Rodriguez's older stuff it's based on is on TechNet at https://gallery.technet.microsoft.com/Privileged-Access-3d072563

Preconfigured policy for the PAWs would be great, there's a load in there and most of it is going to end up being the same everywhere.
