### ISSUE TITLE
Remove OSDFrontEnd reference from modular TS

### ISSUE THREAD

**Issue by motorhead018** [windows-admins/ConfigMgr#88]
Just a quick change, please remove the reference to OSDFrontEnd as it cannot run during a TS, it must be run as a prestart command.
![image](https://user-images.githubusercontent.com/38567415/58030378-0d8d3180-7ae4-11e9-9bb8-fee3127948f9.png)

**Comment by RowdyChildren** [comment]
This is meant to be a placehold for any OSDFrontend.

**Comment by motorhead018** [comment]
While that might be, Nickolaj's OSDFE will only launch as a prestart command.

**Comment by RowdyChildren** [comment]
I don't see any package reference in the current one to Nickolaj's OSD Frontend

**Comment by ajf8729** [comment]
Closing as a nonissue, as this is meant to be a placeholder for any OSD Frontend as noted in the description field.
