### ISSUE TITLE
ZTIGather.wsf sometimes fails to set IsVM properly

### ISSUE THREAD

**Issue by SaltyPeaches** [windows-admins/ConfigMgr#94]
The current ZTIGather script in Task Sequences\Modular OSD\ModularOSD_Files\OSD Configuration\Scripts is 6.3.8443.1000. The issue is resolved in the latest version of the MDT script, 6.3.8456.1000. File attached.

[ZTIGather.zip](https://github.com/winadminsdotorg/SystemCenterConfigMgr/files/3356515/ZTIGather.zip)

**Comment by ajf8729** [comment]
File updated via https://github.com/windows-admins/ConfigMgr/commit/80dfdeb001827bcc15e5ec7e17a6dcb746f3a041
